import { describe, expect, it } from "vitest";
import * as engineApi from "../src/index.ts";

describe("public engine API", () => {
  it("exports extension points without exporting unguarded internal capabilities", () => {
    expect(engineApi).toHaveProperty("BackendRegistry");
    expect(engineApi).toHaveProperty("ArtifactRuntimeRegistry");
    expect(engineApi).toHaveProperty("captureArtifactCode");
    expect(engineApi).toHaveProperty("CompositeSourceBackend");
    expect(engineApi).toHaveProperty("createArtifactManifest");
    expect(engineApi).toHaveProperty("createArtifactRuntimeProvider");
    expect(engineApi).toHaveProperty("createCompositeSource");
    expect(engineApi).toHaveProperty("createHypothesisRegistration");
    expect(engineApi).toHaveProperty("createPromotionCandidate");
    expect(engineApi).toHaveProperty("createSourceManifest");
    expect(engineApi).toHaveProperty("DuckDbFileBackend");
    expect(engineApi).toHaveProperty("executeArtifact");
    expect(engineApi).toHaveProperty("executeWalkForwardWindows");
    expect(engineApi).toHaveProperty("executeWalkForwardContract");
    expect(engineApi).toHaveProperty("createWalkForwardPlan");
    expect(engineApi).toHaveProperty("createVerificationView");
    expect(engineApi).toHaveProperty("createWindowReadSet");
    expect(engineApi).toHaveProperty("loadAdapterFile");
    expect(engineApi).toHaveProperty("ReadSetSnapshotStore");
    expect(engineApi).toHaveProperty("ReadSetSnapshotRecovery");
    expect(engineApi).toHaveProperty("openReadSetSnapshotRecovery");
    expect(engineApi).toHaveProperty("runVeilDataCli");
    expect(engineApi).toHaveProperty("VeilDataService");
    expect(engineApi).toHaveProperty("verifySourceManifest");
    expect(engineApi).toHaveProperty("verifyArtifactCode");
    expect(engineApi).toHaveProperty("verifyArtifactManifest");
    expect(engineApi).toHaveProperty("validateArtifactProtocol");
    expect(engineApi).toHaveProperty("verifyCompositeSource");
    expect(engineApi).toHaveProperty("verifyCompositeSourceManifest");
    expect(engineApi).toHaveProperty("verifyHypothesisRegistration");
    expect(engineApi).toHaveProperty("verifyPromotionCandidate");
    expect(engineApi).toHaveProperty("verifyWalkForwardContractRecord");
    expect(engineApi).toHaveProperty("verifyVerificationView");
    expect(engineApi).toHaveProperty("TemporalGuard");
    expect(engineApi).not.toHaveProperty("readRegisteredBackend");
    expect(engineApi).not.toHaveProperty("resolveSourceBinding");
    expect(engineApi).not.toHaveProperty("selectArtifactRuntimeProvider");
    expect(engineApi).not.toHaveProperty("executeArtifactWithEvidence");
    expect(engineApi).not.toHaveProperty("createWalkForwardRunRecord");
    expect(engineApi).not.toHaveProperty("createWalkForwardWindowExecutionRecord");
    expect(engineApi).not.toHaveProperty("createWalkForwardContractRecord");
    expect(engineApi).not.toHaveProperty("createWalkForwardContractExecutionRecord");
    expect(engineApi).not.toHaveProperty("parameterLockHashForArtifact");
    expect(engineApi).not.toHaveProperty("readSetIdentityCacheForGuard");
    expect(engineApi).not.toHaveProperty("createVerificationViewWithIdentityCache");
  });
});
