export type EngineConfigurationErrorCode =
  | "ADAPTER_LOAD_FAILED"
  | "INVALID_BACKEND"
  | "INVALID_BACKEND_ID"
  | "DUPLICATE_BACKEND"
  | "BACKEND_NOT_FOUND"
  | "BACKEND_SOURCE_UNSUPPORTED"
  | "BACKEND_READ_FAILED"
  | "INVALID_SOURCE"
  | "SOURCE_CHANGED"
  | "INVALID_SOURCE_MANIFEST"
  | "INVALID_COMPOSITE_SOURCE"
  | "BINDING_BACKEND_MISMATCH"
  | "INVALID_BINDING"
  | "INVALID_QUERY"
  | "INVALID_BACKEND_RESULT"
  | "INVALID_READ_SET"
  | "INVALID_SNAPSHOT_STORE"
  | "SNAPSHOT_NOT_FOUND"
  | "INVALID_SNAPSHOT"
  | "SNAPSHOT_RECOVERY_BUSY"
  | "SNAPSHOT_RECOVERY_REFUSED"
  | "INVALID_SNAPSHOT_RECOVERY"
  | "INVALID_ARTIFACT_CODE"
  | "ARTIFACT_CODE_CHANGED"
  | "INVALID_ARTIFACT"
  | "INVALID_ARTIFACT_RUNTIME"
  | "DUPLICATE_ARTIFACT_RUNTIME"
  | "ARTIFACT_RUNTIME_NOT_FOUND"
  | "ARTIFACT_RUNTIME_UNSUPPORTED"
  | "INVALID_ARTIFACT_EXECUTION"
  | "ARTIFACT_EXECUTION_FAILED"
  | "ARTIFACT_EXECUTION_TIMEOUT"
  | "ARTIFACT_EXECUTION_ABORTED"
  | "ARTIFACT_OUTPUT_LIMIT"
  | "INVALID_ARTIFACT_OUTPUT"
  | "INVALID_WALK_FORWARD_PLAN"
  | "INVALID_WINDOW_READ_SET"
  | "INVALID_WALK_FORWARD_EXECUTION"
  | "EMPTY_VERIFICATION_WINDOW"
  | "INVALID_VERIFICATION_VIEW"
  | "INVALID_WALK_FORWARD_CONTRACT"
  | "INVALID_HYPOTHESIS_REGISTRATION"
  | "INVALID_PROMOTION_CANDIDATE";

export class EngineConfigurationError extends Error {
  readonly code: EngineConfigurationErrorCode;
  readonly remedy: string;

  constructor(code: EngineConfigurationErrorCode, message: string, remedy: string) {
    super(`[${code}] ${message}`);
    this.name = "EngineConfigurationError";
    this.code = code;
    this.remedy = remedy;
  }
}
